version: '3.3'
services:
  foodgram_api:
    container_name: foodgram_api
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  foodgram_server:
    container_name: foodgram_server
    build:
      context: ../
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - foodgram_api